# netlify.toml

[build]
  command = "npm run build"  # Adjust the build command based on your project
  publish = "build"          # Adjust the publish directory based on your project

[context.production.environment]
  NODE_ENV = "production"

[context.split1]
  command = "npm run build"
  publish = "build"
  # Add more contexts or customize as needed
